import os
import datetime
import markdown as md
from io import BytesIO
from xhtml2pdf import pisa

PDF_CSS = """
@page {
    size: A4;
    margin: 2cm;
}
body {
    font-family: Helvetica, Arial, sans-serif;
    color: #2b2b2b;
    line-height: 1.5;
    font-size: 11pt;
}
h1 {
    color: #0b5e59;
    border-bottom: 3px solid #0b5e59;
    padding-bottom: 8px;
    font-size: 22pt;
}
h2 {
    color: #0b5e59;
    margin-top: 24px;
    font-size: 15pt;
    border-left: 5px solid #f2a541;
    padding-left: 10px;
}
h3 {
    color: #333;
    font-size: 12.5pt;
    margin-top: 16px;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
    font-size: 9.5pt;
}
th {
    background-color: #0b5e59;
    color: white;
    padding: 6px 8px;
    text-align: left;
}
td {
    padding: 6px 8px;
    border-bottom: 1px solid #ddd;
}
a {
    color: #0b5e59;
    text-decoration: none;
}
hr {
    border: none;
    border-top: 1px solid #ccc;
    margin: 20px 0;
}
.meta {
    color: #777;
    font-size: 9.5pt;
    margin-bottom: 20px;
}
"""


def _build_markdown_content(response_text: str) -> str:
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')
    return f"""# 🌍 AI Travel Plan

**Generated:** {timestamp}
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""


def save_document(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to a Markdown file. Returns the file path."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)

    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        print(f"Markdown file saved as: {filename}")
        return filename
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None


def save_document_pdf(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to a styled PDF file using xhtml2pdf (pure Python,
    no system dependencies — Windows-friendly). Returns the file path, or None on failure."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)

    try:
        html_body = md.markdown(markdown_content, extensions=["tables", "fenced_code"])
        full_html = f"<html><head><style>{PDF_CSS}</style></head><body>{html_body}</body></html>"

        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.pdf"

        with open(filename, "wb") as f:
            result = pisa.CreatePDF(src=full_html, dest=f)

        if result.err:
            print(f"xhtml2pdf reported {result.err} error(s) while generating PDF")
            return None

        print(f"PDF file saved as: {filename}")
        return filename
    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return None