import os
import re
import datetime
import markdown as md
from io import BytesIO
from xhtml2pdf import pisa

# Matches emoji / pictographic characters that xhtml2pdf's default font can't render
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F300-\U0001FAFF"   # symbols, pictographs, emoticons, transport
    "\U00002600-\U000027BF"   # misc symbols & dingbats
    "\U0001F1E6-\U0001F1FF"   # regional indicator symbols
    "\U0000FE0F"              # variation selector (used after some emoji)
    "\U000020E3"              # combining keycap (used in 1️⃣ 2️⃣ 3️⃣ style numbering)
    "]+",
    flags=re.UNICODE,
)

# ALL Unicode dash/hyphen variants -> plain ASCII hyphen.
# LLM output commonly uses U+2011 (non-breaking hyphen) instead of a plain "-",
# which is exactly what was causing "3■Day", "Wi■Fi", "off■beat" etc.

DASH_PATTERN = re.compile("[\u2010\u2011\u2012\u2013\u2014\u2015\u2212]")

# "Smart"/typographic characters and common currency symbols that fall outside
# xhtml2pdf's default font support
CHAR_REPLACEMENTS = {
    "\u2011": "-",
    "\u2013": "-",
    "\u2014": "--",
    "\u2018": "'", "\u2019": "'",
    "\u201c": '"', "\u201d": '"',
    "\u2026": "...",
    "\u00a0": " ",
    "\u20b9": "Rs.",   # Indian Rupee sign (₹)
    "\u20a8": "Rs.",   # Rupee sign (₨)
    "\u0e3f": "Baht",  # Thai Baht sign
    "\u00a3": "GBP",   # £ (only needed if you ever swap fonts that don't support it)
}

def _sanitize_for_pdf(text: str) -> str:
    """Strip emoji, replace typographic/currency characters that xhtml2pdf can't
    render, then strip ANY remaining character outside the font's safe range as
    a catch-all — so no future unexpected character can produce a '■' again."""
    text = EMOJI_PATTERN.sub("", text)
    text = DASH_PATTERN.sub("-", text)
    for bad, good in CHAR_REPLACEMENTS.items():
        text = text.replace(bad, good)
    # Safety net: xhtml2pdf's default font reliably covers only Latin-1 (ord <= 255).
    # Anything left above that at this point is a character we haven't explicitly
    # mapped — drop it rather than let it render as a square.
    text = "".join(ch for ch in text if ord(ch) <= 255)
    # collapse extra spaces left behind where emoji were removed
    text = re.sub(r"[ \t]{2,}", " ", text)
    text = "\n".join(line.strip() for line in text.split("\n"))
    return text


PDF_CSS = """
@page {
    size: A4;
    margin: 2cm;
}
body {
    font-family: Helvetica, Arial, sans-serif;
    color: #2b2b2b;
    line-height: 1.5;
    font-size: 11pt;
}
h1 {
    color: #0b5e59;
    border-bottom: 3px solid #0b5e59;
    padding-bottom: 8px;
    font-size: 22pt;
}
h2 {
    color: #0b5e59;
    margin-top: 24px;
    font-size: 15pt;
    border-left: 5px solid #f2a541;
    padding-left: 10px;
}
h3 {
    color: #333;
    font-size: 12.5pt;
    margin-top: 16px;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 12px 0;
    font-size: 9.5pt;
}
th {
    background-color: #0b5e59;
    color: white;
    padding: 6px 8px;
    text-align: left;
}
td {
    padding: 6px 8px;
    border-bottom: 1px solid #ddd;
}
a {
    color: #0b5e59;
    text-decoration: none;
}
hr {
    border: none;
    border-top: 1px solid #ccc;
    margin: 20px 0;
}
.meta {
    color: #777;
    font-size: 9.5pt;
    margin-bottom: 20px;
}
"""


def _build_markdown_content(response_text: str) -> str:
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')
    return f"""# 🌍 AI Travel Plan

**Generated:** {timestamp}
**Created by:** Atriyo's Travel Agent

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""


def save_document(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to a Markdown file. Returns the file path."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)

    try:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{timestamp}.md"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        print(f"Markdown file saved as: {filename}")
        return filename
    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None


def save_document_pdf(response_text: str, directory: str = "./output") -> str:
    """Export travel plan to a styled PDF file using xhtml2pdf (pure Python,
    no system dependencies — Windows-friendly). Returns the file path, or None on failure."""
    os.makedirs(directory, exist_ok=True)
    markdown_content = _build_markdown_content(response_text)
    # Build with a plain, PDF-safe title/footer (no emoji) since xhtml2pdf can't render them
    timestamp = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')
    pdf_source = f"""# AI Travel Plan

    **Generated:** {timestamp}
    **Created by:** Atriyo's Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """
    pdf_source = _sanitize_for_pdf(pdf_source)

    try:
        html_body = md.markdown(pdf_source, extensions=["tables", "fenced_code"])
        full_html = f"<html><head><style>{PDF_CSS}</style></head><body>{html_body}</body></html>"

        out_timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"{directory}/AI_Trip_Planner_{out_timestamp}.pdf"

        with open(filename, "wb") as f:
            result = pisa.CreatePDF(src=full_html, dest=f)

        if result.err:
            print(f"xhtml2pdf reported {result.err} error(s) while generating PDF")
            return None

        print(f"PDF file saved as: {filename}")
        return filename
    except Exception as e:
        print(f"Error saving PDF file: {e}")
        return None