[project]
name = "trip-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sarasi", email = "eg245387@engug.ruh.ac.lk" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-sqlite",
    "pandas>=3.0.5",
    "langchain",
    "langchain-community",
    "langchain-groq",
    "langchain-openai",
    "langchain-google-community[places]",
    "langchain-tavily",
    "pydantic",
    "python-dotenv",
    "httpx",
    "requests",
    "xhtml2pdf",
    "markdown",
]

[project.scripts]
trip-planner = "trip_planner:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
